logging:
  level:
    org.springframework: error
    org.springframework.security: debug

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oauth-database
      username: admin
      password: admin
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
